#ifndef _CMSIS_CONFIG_H_
#define _CMSIS_CONFIG_H_

//#define CMSIS_PTHREAD_SCHED_REALTIME
#ifdef CMSIS_PTHREAD_SCHED_REALTIME
#define CMSIS_PTHREAD_SCHED_POLICY  SCHED_RR
#define CMSIS_PTHREAD_PRIOLITY_MAX 99
#define CMSIS_PTHREAD_PRIOLITY_MIN 1
#define CMSIS_PTHREAD_GET_PRIORITY(cmsis_priority) ( CMSIS_PTHREAD_PRIOLITY_MAX - (osPriorityRealtime7 - (cmsis_priority)) )
#endif /* CMSIS_PTHREAD_SCHED_REALTIME */

#endif /* _CMSIS_CONFIG_H_ */